# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17inventory_service.proto\x12\tinventory\"[\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x02(\t\x12\r\n\x05genre\x18\x04 \x02(\t\x12\x17\n\x0fpublishing_year\x18\x05 \x02(\x05\"u\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x02(\x05\x12\x1f\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x0f.inventory.BookH\x00\x12!\n\x06status\x18\x03 \x02(\x0e\x32\x11.inventory.StatusB\x06\n\x04item\"7\n\x12\x43reateBookResponse\x12!\n\x06status\x18\x01 \x02(\x0e\x32\x11.inventory.Status\"2\n\x11\x43reateBookRequest\x12\x1d\n\x04\x62ook\x18\x01 \x02(\x0b\x32\x0f.inventory.Book\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x02(\t\"\\\n\x0fGetBookResponse\x12!\n\x06status\x18\x01 \x02(\x0e\x32\x11.inventory.Status\x12&\n\x04item\x18\x02 \x01(\x0b\x32\x18.inventory.InventoryItem*G\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_SUCCESS\x10\x01\x12\x11\n\rSTATUS_FAILED\x10\x02\x32\x9f\x01\n\x10InventoryService\x12I\n\nCreateBook\x12\x1c.inventory.CreateBookRequest\x1a\x1d.inventory.CreateBookResponse\x12@\n\x07GetBook\x12\x19.inventory.GetBookRequest\x1a\x1a.inventory.GetBookResponse')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=485
  _STATUS._serialized_end=556
  _BOOK._serialized_start=38
  _BOOK._serialized_end=129
  _INVENTORYITEM._serialized_start=131
  _INVENTORYITEM._serialized_end=248
  _CREATEBOOKRESPONSE._serialized_start=250
  _CREATEBOOKRESPONSE._serialized_end=305
  _CREATEBOOKREQUEST._serialized_start=307
  _CREATEBOOKREQUEST._serialized_end=357
  _GETBOOKREQUEST._serialized_start=359
  _GETBOOKREQUEST._serialized_end=389
  _GETBOOKRESPONSE._serialized_start=391
  _GETBOOKRESPONSE._serialized_end=483
  _INVENTORYSERVICE._serialized_start=559
  _INVENTORYSERVICE._serialized_end=718
# @@protoc_insertion_point(module_scope)
